<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Position;
use App\Models\Department;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get departments
        $adminDept = Department::where('code', 'ADMIN')->first();
        $hrDept = Department::where('code', 'HR')->first();
        $financeDept = Department::where('code', 'FIN')->first();
        $itDept = Department::where('code', 'IT')->first();
        $opsDept = Department::where('code', 'OPS')->first();
        $mktDept = Department::where('code', 'MKT')->first();
        $csDept = Department::where('code', 'CS')->first();
        $legalDept = Department::where('code', 'LEGAL')->first();

        $positions = [
            // Administration Department
            [
                'title' => 'Chief Executive Officer',
                'code' => 'CEO',
                'description' => 'Top executive responsible for overall strategic direction and management',
                'department_id' => $adminDept->id ?? null,
                'min_salary' => 5000000,
                'max_salary' => 10000000,
                'employment_type' => 'permanent',
                'requirements' => 'Master\'s degree in Business Administration or related field, 15+ years executive experience',
                'responsibilities' => 'Strategic planning, organizational leadership, stakeholder management, decision making',
            ],
            [
                'title' => 'Chief Operating Officer',
                'code' => 'COO',
                'description' => 'Senior executive overseeing daily operations',
                'department_id' => $adminDept->id ?? null,
                'min_salary' => 4000000,
                'max_salary' => 8000000,
                'employment_type' => 'permanent',
                'requirements' => 'Master\'s degree, 10+ years management experience',
                'responsibilities' => 'Operations management, process improvement, team leadership',
            ],
            [
                'title' => 'Executive Assistant',
                'code' => 'EXEC-ASST',
                'description' => 'Administrative support to senior executives',
                'department_id' => $adminDept->id ?? null,
                'min_salary' => 800000,
                'max_salary' => 1500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree, excellent communication skills, 3+ years experience',
                'responsibilities' => 'Calendar management, document preparation, meeting coordination',
            ],
            [
                'title' => 'Administrative Officer',
                'code' => 'ADMIN-OFF',
                'description' => 'General administrative duties and office management',
                'department_id' => $adminDept->id ?? null,
                'min_salary' => 600000,
                'max_salary' => 1200000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Business Administration or related field',
                'responsibilities' => 'Office administration, record keeping, facility management',
            ],
            [
                'title' => 'Receptionist',
                'code' => 'RECEPT',
                'description' => 'Front desk reception and customer service',
                'department_id' => $adminDept->id ?? null,
                'min_salary' => 400000,
                'max_salary' => 800000,
                'employment_type' => 'permanent',
                'requirements' => 'High school diploma, excellent communication skills',
                'responsibilities' => 'Greeting visitors, answering phones, directing inquiries',
            ],

            // Human Resources Department
            [
                'title' => 'Human Resources Manager',
                'code' => 'HR-MGR',
                'description' => 'Oversees all HR functions and strategies',
                'department_id' => $hrDept->id ?? null,
                'min_salary' => 2500000,
                'max_salary' => 4500000,
                'employment_type' => 'permanent',
                'requirements' => 'Master\'s degree in HR or related field, 8+ years HR experience',
                'responsibilities' => 'HR strategy, recruitment, employee relations, policy development',
            ],
            [
                'title' => 'HR Officer',
                'code' => 'HR-OFF',
                'description' => 'Handles day-to-day HR operations',
                'department_id' => $hrDept->id ?? null,
                'min_salary' => 1200000,
                'max_salary' => 2200000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in HR or related field, 3+ years experience',
                'responsibilities' => 'Recruitment, onboarding, payroll support, employee records',
            ],
            [
                'title' => 'Recruitment Specialist',
                'code' => 'RECRUIT',
                'description' => 'Specializes in talent acquisition and recruitment',
                'department_id' => $hrDept->id ?? null,
                'min_salary' => 1000000,
                'max_salary' => 1800000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree, 2+ years recruitment experience',
                'responsibilities' => 'Job posting, candidate screening, interviews, offer management',
            ],
            [
                'title' => 'Payroll Administrator',
                'code' => 'PAYROLL',
                'description' => 'Manages employee payroll and benefits',
                'department_id' => $hrDept->id ?? null,
                'min_salary' => 900000,
                'max_salary' => 1600000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Accounting or HR, payroll experience',
                'responsibilities' => 'Payroll processing, benefits administration, tax compliance',
            ],
            [
                'title' => 'Training and Development Officer',
                'code' => 'TRAIN-DEV',
                'description' => 'Develops and delivers employee training programs',
                'department_id' => $hrDept->id ?? null,
                'min_salary' => 1000000,
                'max_salary' => 1800000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree, training experience, excellent presentation skills',
                'responsibilities' => 'Training needs analysis, program development, delivery and evaluation',
            ],

            // Finance Department
            [
                'title' => 'Chief Financial Officer',
                'code' => 'CFO',
                'description' => 'Senior executive responsible for financial strategy',
                'department_id' => $financeDept->id ?? null,
                'min_salary' => 4500000,
                'max_salary' => 8500000,
                'employment_type' => 'permanent',
                'requirements' => 'Master\'s degree in Finance or Accounting, CPA, 12+ years experience',
                'responsibilities' => 'Financial planning, budgeting, financial reporting, risk management',
            ],
            [
                'title' => 'Finance Manager',
                'code' => 'FIN-MGR',
                'description' => 'Manages finance department operations',
                'department_id' => $financeDept->id ?? null,
                'min_salary' => 2500000,
                'max_salary' => 4500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Finance or Accounting, CPA preferred, 8+ years experience',
                'responsibilities' => 'Financial management, budgeting, reporting, team supervision',
            ],
            [
                'title' => 'Accountant',
                'code' => 'ACCT',
                'description' => 'Handles accounting and financial records',
                'department_id' => $financeDept->id ?? null,
                'min_salary' => 1200000,
                'max_salary' => 2200000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Accounting, 3+ years experience',
                'responsibilities' => 'Bookkeeping, financial statements, tax preparation, audits',
            ],
            [
                'title' => 'Senior Accountant',
                'code' => 'SR-ACCT',
                'description' => 'Senior level accounting with advanced responsibilities',
                'department_id' => $financeDept->id ?? null,
                'min_salary' => 1800000,
                'max_salary' => 3000000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Accounting, CPA preferred, 5+ years experience',
                'responsibilities' => 'Complex accounting tasks, financial analysis, mentoring junior staff',
            ],
            [
                'title' => 'Accounts Payable Officer',
                'code' => 'AP-OFF',
                'description' => 'Manages vendor payments and accounts payable',
                'department_id' => $financeDept->id ?? null,
                'min_salary' => 800000,
                'max_salary' => 1400000,
                'employment_type' => 'permanent',
                'requirements' => 'Diploma or Bachelor\'s in Accounting, 2+ years experience',
                'responsibilities' => 'Invoice processing, payment processing, vendor relations',
            ],
            [
                'title' => 'Accounts Receivable Officer',
                'code' => 'AR-OFF',
                'description' => 'Manages customer invoicing and collections',
                'department_id' => $financeDept->id ?? null,
                'min_salary' => 800000,
                'max_salary' => 1400000,
                'employment_type' => 'permanent',
                'requirements' => 'Diploma or Bachelor\'s in Accounting, 2+ years experience',
                'responsibilities' => 'Invoice generation, payment tracking, collections',
            ],
            [
                'title' => 'Financial Analyst',
                'code' => 'FIN-ANAL',
                'description' => 'Analyzes financial data and trends',
                'department_id' => $financeDept->id ?? null,
                'min_salary' => 1500000,
                'max_salary' => 2500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Finance or Economics, analytical skills, 3+ years experience',
                'responsibilities' => 'Financial analysis, forecasting, budgeting support, reporting',
            ],
            [
                'title' => 'Internal Auditor',
                'code' => 'AUDITOR',
                'description' => 'Conducts internal audits and compliance reviews',
                'department_id' => $financeDept->id ?? null,
                'min_salary' => 1800000,
                'max_salary' => 3000000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Accounting, CIA preferred, 4+ years audit experience',
                'responsibilities' => 'Internal audits, risk assessment, compliance reviews, recommendations',
            ],

            // Information Technology Department
            [
                'title' => 'IT Manager',
                'code' => 'IT-MGR',
                'description' => 'Manages IT department and technology infrastructure',
                'department_id' => $itDept->id ?? null,
                'min_salary' => 2500000,
                'max_salary' => 4500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in IT or Computer Science, 8+ years IT experience',
                'responsibilities' => 'IT strategy, infrastructure management, team leadership, security',
            ],
            [
                'title' => 'Systems Administrator',
                'code' => 'SYS-ADMIN',
                'description' => 'Manages server infrastructure and systems',
                'department_id' => $itDept->id ?? null,
                'min_salary' => 1500000,
                'max_salary' => 2500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in IT, server administration experience, 4+ years',
                'responsibilities' => 'Server management, network administration, system maintenance',
            ],
            [
                'title' => 'Software Developer',
                'code' => 'DEV',
                'description' => 'Develops and maintains software applications',
                'department_id' => $itDept->id ?? null,
                'min_salary' => 1500000,
                'max_salary' => 3000000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Computer Science or related, programming skills, 3+ years',
                'responsibilities' => 'Software development, coding, testing, documentation',
            ],
            [
                'title' => 'Senior Software Developer',
                'code' => 'SR-DEV',
                'description' => 'Senior level software development and architecture',
                'department_id' => $itDept->id ?? null,
                'min_salary' => 2500000,
                'max_salary' => 4000000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Computer Science, 6+ years development experience',
                'responsibilities' => 'System architecture, complex development, code reviews, mentoring',
            ],
            [
                'title' => 'IT Support Specialist',
                'code' => 'IT-SUPP',
                'description' => 'Provides technical support to end users',
                'department_id' => $itDept->id ?? null,
                'min_salary' => 800000,
                'max_salary' => 1400000,
                'employment_type' => 'permanent',
                'requirements' => 'Diploma or Bachelor\'s in IT, troubleshooting skills, 2+ years experience',
                'responsibilities' => 'Help desk support, troubleshooting, hardware/software maintenance',
            ],
            [
                'title' => 'Database Administrator',
                'code' => 'DBA',
                'description' => 'Manages database systems and data',
                'department_id' => $itDept->id ?? null,
                'min_salary' => 1800000,
                'max_salary' => 3000000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in IT, database certification, 4+ years DBA experience',
                'responsibilities' => 'Database design, maintenance, backup, performance optimization',
            ],
            [
                'title' => 'Network Engineer',
                'code' => 'NET-ENG',
                'description' => 'Designs and maintains network infrastructure',
                'department_id' => $itDept->id ?? null,
                'min_salary' => 1800000,
                'max_salary' => 3000000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in IT, network certifications, 4+ years experience',
                'responsibilities' => 'Network design, configuration, troubleshooting, security',
            ],
            [
                'title' => 'Cybersecurity Specialist',
                'code' => 'CYBER',
                'description' => 'Protects systems and data from security threats',
                'department_id' => $itDept->id ?? null,
                'min_salary' => 2000000,
                'max_salary' => 3500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in IT, security certifications, 4+ years experience',
                'responsibilities' => 'Security monitoring, threat analysis, incident response, compliance',
            ],

            // Operations Department
            [
                'title' => 'Operations Manager',
                'code' => 'OPS-MGR',
                'description' => 'Manages daily operations and logistics',
                'department_id' => $opsDept->id ?? null,
                'min_salary' => 2500000,
                'max_salary' => 4500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Business or Operations, 8+ years experience',
                'responsibilities' => 'Operations management, process optimization, team leadership',
            ],
            [
                'title' => 'Operations Officer',
                'code' => 'OPS-OFF',
                'description' => 'Handles day-to-day operational tasks',
                'department_id' => $opsDept->id ?? null,
                'min_salary' => 1000000,
                'max_salary' => 1800000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree, 2+ years operations experience',
                'responsibilities' => 'Operational tasks, coordination, reporting',
            ],
            [
                'title' => 'Logistics Coordinator',
                'code' => 'LOG-COORD',
                'description' => 'Coordinates logistics and supply chain',
                'department_id' => $opsDept->id ?? null,
                'min_salary' => 1200000,
                'max_salary' => 2000000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Logistics or Supply Chain, 3+ years experience',
                'responsibilities' => 'Supply chain management, inventory, shipping coordination',
            ],
            [
                'title' => 'Procurement Officer',
                'code' => 'PROC',
                'description' => 'Handles purchasing and procurement',
                'department_id' => $opsDept->id ?? null,
                'min_salary' => 1000000,
                'max_salary' => 1800000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree, procurement experience, 2+ years',
                'responsibilities' => 'Vendor management, purchase orders, contract negotiation',
            ],
            [
                'title' => 'Warehouse Supervisor',
                'code' => 'WH-SUP',
                'description' => 'Supervises warehouse operations',
                'department_id' => $opsDept->id ?? null,
                'min_salary' => 1000000,
                'max_salary' => 1800000,
                'employment_type' => 'permanent',
                'requirements' => 'Diploma or Bachelor\'s, warehouse experience, 3+ years',
                'responsibilities' => 'Warehouse management, inventory control, team supervision',
            ],

            // Marketing Department
            [
                'title' => 'Marketing Manager',
                'code' => 'MKT-MGR',
                'description' => 'Manages marketing strategies and campaigns',
                'department_id' => $mktDept->id ?? null,
                'min_salary' => 2500000,
                'max_salary' => 4500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Marketing, 8+ years marketing experience',
                'responsibilities' => 'Marketing strategy, campaign management, brand management',
            ],
            [
                'title' => 'Marketing Officer',
                'code' => 'MKT-OFF',
                'description' => 'Executes marketing activities and campaigns',
                'department_id' => $mktDept->id ?? null,
                'min_salary' => 1000000,
                'max_salary' => 1800000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Marketing, 2+ years experience',
                'responsibilities' => 'Campaign execution, content creation, market research',
            ],
            [
                'title' => 'Digital Marketing Specialist',
                'code' => 'DIG-MKT',
                'description' => 'Specializes in digital marketing and online presence',
                'department_id' => $mktDept->id ?? null,
                'min_salary' => 1200000,
                'max_salary' => 2200000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree, digital marketing certifications, 3+ years experience',
                'responsibilities' => 'Social media, SEO, online advertising, analytics',
            ],
            [
                'title' => 'Brand Manager',
                'code' => 'BRAND-MGR',
                'description' => 'Manages brand identity and positioning',
                'department_id' => $mktDept->id ?? null,
                'min_salary' => 2000000,
                'max_salary' => 3500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Marketing, 5+ years brand management experience',
                'responsibilities' => 'Brand strategy, identity management, brand communications',
            ],
            [
                'title' => 'Content Creator',
                'code' => 'CONTENT',
                'description' => 'Creates marketing content and materials',
                'department_id' => $mktDept->id ?? null,
                'min_salary' => 800000,
                'max_salary' => 1500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree, creative skills, 2+ years experience',
                'responsibilities' => 'Content writing, design, social media content, campaigns',
            ],

            // Customer Service Department
            [
                'title' => 'Customer Service Manager',
                'code' => 'CS-MGR',
                'description' => 'Manages customer service operations',
                'department_id' => $csDept->id ?? null,
                'min_salary' => 2000000,
                'max_salary' => 3500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree, 6+ years customer service experience',
                'responsibilities' => 'Team management, service standards, customer satisfaction',
            ],
            [
                'title' => 'Customer Service Representative',
                'code' => 'CS-REP',
                'description' => 'Handles customer inquiries and support',
                'department_id' => $csDept->id ?? null,
                'min_salary' => 600000,
                'max_salary' => 1200000,
                'employment_type' => 'permanent',
                'requirements' => 'High school diploma or Bachelor\'s, excellent communication skills',
                'responsibilities' => 'Customer support, issue resolution, order processing',
            ],
            [
                'title' => 'Call Center Agent',
                'code' => 'CALL-AGENT',
                'description' => 'Handles phone-based customer support',
                'department_id' => $csDept->id ?? null,
                'min_salary' => 500000,
                'max_salary' => 1000000,
                'employment_type' => 'permanent',
                'requirements' => 'High school diploma, phone communication skills',
                'responsibilities' => 'Phone support, customer inquiries, order taking',
            ],
            [
                'title' => 'Customer Relations Officer',
                'code' => 'CS-REL',
                'description' => 'Builds and maintains customer relationships',
                'department_id' => $csDept->id ?? null,
                'min_salary' => 1000000,
                'max_salary' => 1800000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree, 3+ years customer relations experience',
                'responsibilities' => 'Relationship building, account management, customer retention',
            ],

            // Legal Department
            [
                'title' => 'Legal Manager',
                'code' => 'LEGAL-MGR',
                'description' => 'Manages legal affairs and compliance',
                'department_id' => $legalDept->id ?? null,
                'min_salary' => 3000000,
                'max_salary' => 5500000,
                'employment_type' => 'permanent',
                'requirements' => 'Law degree, admitted to practice, 8+ years legal experience',
                'responsibilities' => 'Legal strategy, contract review, compliance, litigation management',
            ],
            [
                'title' => 'Legal Officer',
                'code' => 'LEGAL-OFF',
                'description' => 'Handles legal matters and documentation',
                'department_id' => $legalDept->id ?? null,
                'min_salary' => 1500000,
                'max_salary' => 2800000,
                'employment_type' => 'permanent',
                'requirements' => 'Law degree, admitted to practice, 3+ years experience',
                'responsibilities' => 'Legal research, document drafting, contract review, compliance',
            ],
            [
                'title' => 'Compliance Officer',
                'code' => 'COMPLIANCE',
                'description' => 'Ensures regulatory compliance',
                'department_id' => $legalDept->id ?? null,
                'min_salary' => 1500000,
                'max_salary' => 2500000,
                'employment_type' => 'permanent',
                'requirements' => 'Bachelor\'s degree in Law or related, 3+ years compliance experience',
                'responsibilities' => 'Compliance monitoring, risk assessment, policy development',
            ],
            [
                'title' => 'Paralegal',
                'code' => 'PARALEGAL',
                'description' => 'Supports legal team with research and documentation',
                'department_id' => $legalDept->id ?? null,
                'min_salary' => 800000,
                'max_salary' => 1500000,
                'employment_type' => 'permanent',
                'requirements' => 'Diploma or Bachelor\'s in Law, 2+ years paralegal experience',
                'responsibilities' => 'Legal research, document preparation, case management',
            ],

            // General/Cross-Department Positions
            [
                'title' => 'Head of Department',
                'code' => 'HOD',
                'description' => 'Department head responsible for department strategy and management',
                'department_id' => null,
                'min_salary' => 3000000,
                'max_salary' => 6000000,
                'employment_type' => 'permanent',
                'requirements' => 'Master\'s degree, 10+ years management experience',
                'responsibilities' => 'Department leadership, strategy, team management, budget oversight',
            ],
            [
                'title' => 'Intern',
                'code' => 'INTERN',
                'description' => 'Entry-level position for learning and gaining experience',
                'department_id' => null,
                'min_salary' => 300000,
                'max_salary' => 600000,
                'employment_type' => 'intern',
                'requirements' => 'Currently pursuing or recently completed degree',
                'responsibilities' => 'Learning, supporting team projects, administrative tasks',
            ],
            [
                'title' => 'Contract Staff',
                'code' => 'CONTRACT',
                'description' => 'Temporary contract position',
                'department_id' => null,
                'min_salary' => 500000,
                'max_salary' => 2000000,
                'employment_type' => 'contract',
                'requirements' => 'Varies by role',
                'responsibilities' => 'Project-based work, temporary assignments',
            ],
        ];

        foreach ($positions as $position) {
            Position::updateOrCreate(
                ['code' => $position['code']],
                $position
            );
        }

        $this->command->info('Positions seeded successfully!');
    }
}
