<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Tax Report - {{ $startDate }} to {{ $endDate }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .section {
            margin-bottom: 25px;
        }
        .section-title {
            background-color: #667eea;
            color: white;
            padding: 10px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        table th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .summary-box {
            background-color: #f9f9f9;
            padding: 15px;
            border-left: 4px solid #667eea;
            margin-bottom: 20px;
        }
        .summary-box h3 {
            margin-top: 0;
            color: #667eea;
        }
        .total-row {
            font-weight: bold;
            background-color: #f0f0f0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Tax Return Report</h1>
        <p><strong>Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('F d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('F d, Y') }}</p>
        <p><strong>Generated:</strong> {{ now()->format('F d, Y h:i A') }}</p>
    </div>

    <div class="section">
        <div class="section-title">VAT Summary</div>
        <table>
            <tr>
                <th>Description</th>
                <th class="text-right">Amount (TZS)</th>
            </tr>
            <tr>
                <td>VAT Collected</td>
                <td class="text-right">{{ number_format($vatCollected, 2) }}</td>
            </tr>
            <tr>
                <td>VAT Paid</td>
                <td class="text-right">{{ number_format($vatPaid, 2) }}</td>
            </tr>
            <tr class="total-row">
                <td>Net VAT</td>
                <td class="text-right">{{ number_format($vatNet, 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">PAYE Summary</div>
        <div class="summary-box">
            <h3>Total PAYE Collected: TZS {{ number_format($payeTotal, 2) }}</h3>
            <p>This amount represents the total Pay As You Earn tax deducted from employee salaries during the reporting period.</p>
        </div>
    </div>

    <div class="section">
        <div class="summary-box">
            <h3>Overall Tax Summary</h3>
            <table>
                <tr>
                    <td><strong>Total Tax Collected (VAT)</strong></td>
                    <td class="text-right"><strong>TZS {{ number_format($vatCollected, 2) }}</strong></td>
                </tr>
                <tr>
                    <td><strong>Total Tax Paid (VAT)</strong></td>
                    <td class="text-right"><strong>TZS {{ number_format($vatPaid, 2) }}</strong></td>
                </tr>
                <tr>
                    <td><strong>PAYE Collected</strong></td>
                    <td class="text-right"><strong>TZS {{ number_format($payeTotal, 2) }}</strong></td>
                </tr>
                <tr class="total-row">
                    <td><strong>Net Tax Owed</strong></td>
                    <td class="text-right"><strong>TZS {{ number_format($vatCollected - $vatPaid + $payeTotal, 2) }}</strong></td>
                </tr>
            </table>
        </div>
    </div>

    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #666; font-size: 10px;">
        <p>This is a computer-generated report. No signature required.</p>
        <p>Generated by OfisiLink Accounting System</p>
    </div>
</body>
</html>




